" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

" Behavior
syntax on

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set number
set mouse=a

" Keybindings
nnoremap <F4> :make!<cr>

" Commands
cmap w!! w !sudo tee > /dev/null % " write to file when forgot to sudo

" Package settings
" Automatically install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Vim-plug section ###########################################################
call plug#begin('~/.vim/plugged')

Plug 'arcticicestudio/nord-vim' " color theme
Plug 'vim-airline/vim-airline' " statusline
Plug 'valloric/youcompleteme' " autocompletion
"Plug 'tpope/vim-commentary' " easy commenting
Plug 'scrooloose/nerdcommenter' " easier commenting
Plug 'scrooloose/nerdtree' " file explorer 
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " fuzzy finder
Plug 'tpope/vim-fugitive' " integrated Git
Plug 'airblade/vim-gitgutter' " git diff in sign column


call plug#end()
"#############################################################################

" Colorscheme
colorscheme nord

" vim-latex-live-preview
let g:livepreview_previewer = 'evince'

" airline
let g:airline_powerline_fonts = 1
