import = ["~/.config/alacritty/themes/themes/pastel_dark.toml"]
#import = ["~/.config/alacritty/themes/themes/ashes_light.toml"]
#import = ["~/.config/alacritty/themes/themes/catppuccin-mocha.toml"]
#import = ["~/.config/alacritty/themes/themes/catppuccin-latte.toml"]
#import = ["~/.config/alacritty/themes/themes/xterm.toml"]

[font]
size = 12.2

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[font.italic]
family = "Terminess Nerd Font"
style = "Regular" # Italics disabled

[mouse]
hide_when_typing = true

[cursor.style]
blinking = "Always"

[cursor.vi_mode_style]
blinking = "Always"

[cursor]
blink_interval = 80
blink_timeout = 1

[bell]
animation             = "EaseOutExpo"
duration              = 0
color                 = "#C0C5CE"
#command               = { program = "notify-send", args = ["alacritty", "bell",] }

[window]
decorations = "None"
#opacity = 0.95

[window.dimensions]
columns = 140
lines = 30 

[env]
TERM = "xterm-256color"

