#import = ["~/.config/alacritty/themes/themes/dracula.toml"]
#import = ["~/.config/alacritty/themes/themes/monokai_charcoal.toml"]
import = ["~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]
#import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]

[font]
size = 13.5

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[font.italic]
family = "Terminess Nerd Font"
style = "Regular" # Italics disabled

[mouse]
hide_when_typing = true

[cursor.style]
blinking = "Always"

[cursor.vi_mode_style]
blinking = "Always"

[cursor]
blink_interval = 80
blink_timeout = 1

[bell]
animation             = "EaseOutExpo"
duration              = 0
color                 = "#C0C5CE"
#command               = { program = "notify-send", args = ["alacritty", "bell",] }

[window.dimensions]
columns = 140
lines = 30 
