#!/bin/bash

# Sets the Wacom tablet to only use the laptop screen
#xsetwacom set 'Wacom Intuos BT S Pad pad'  MapToOutput eDP1
xsetwacom set 'Wacom Intuos BT S Pen stylus' MapToOutput eDP1
xsetwacom set 'Wacom Intuos BT S Pad pad' Button 1 "key +ctrl z -ctrl"
xsetwacom set 'Wacom Intuos BT S Pad pad' Button 2 "key +ctrl y -ctrl"
xsetwacom set 'Wacom Intuos BT S Pad pad' Button 3 "key pgup"
xsetwacom set 'Wacom Intuos BT S Pad pad' Button 8 "key pgdn"

